server:
  port: 8082

spring:
  application:
    name: t4-concurrencia-kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: t4-group
      auto-offset-reset: earliest
    producer:
      retries: 0

app:
  executor:
    core-pool-size: 4
    max-pool-size: 8
    queue-capacity: 100
  kafka:
    topic-transacciones: transacciones-entrada
    topic-resultados: transacciones-resultados
